INSERT OR IGNORE INTO categories (id, name, icon, sort_order, is_system) VALUES
  ('cat-travel', 'Travel essentials', '🧭', 10, 1),
  ('cat-business', 'Business trip', '💼', 20, 1),
  ('cat-electronics', 'Electronics', '🔌', 30, 1),
  ('cat-shoes', 'Shoes', '👟', 40, 1),
  ('cat-clothes', 'Clothes', '👕', 50, 1),
  ('cat-beach', 'Beach', '🏖️', 60, 1),
  ('cat-adventure', 'Adventure & outdoors', '🥾', 70, 1),
  ('cat-camera', 'Camera', '📷', 80, 1),
  ('cat-toiletries', 'Toiletries', '🪥', 90, 1),
  ('cat-medication', 'Medication & health', '💊', 100, 1),
  ('cat-comfort', 'Travel comfort', '😴', 110, 1),
  ('cat-misc', 'Miscellaneous', '📦', 120, 1);

INSERT OR IGNORE INTO items (id, name, category_id, default_quantity, is_essential) VALUES
  ('item-passport', 'Passport', 'cat-travel', 1, 1),
  ('item-id-card', 'Identity card', 'cat-travel', 1, 1),
  ('item-esim', 'eSIM', 'cat-travel', 1, 1),
  ('item-money', 'Money / cards', 'cat-travel', 1, 1),
  ('item-water-bottle', 'Water bottle', 'cat-travel', 1, 0),
  ('item-snacks', 'Snacks', 'cat-travel', 1, 0),

  ('item-suit', 'Suit', 'cat-business', 1, 0),
  ('item-shirts', 'Business shirts', 'cat-business', 3, 0),
  ('item-slacks', 'Slacks', 'cat-business', 2, 0),
  ('item-laptop', 'Laptop', 'cat-business', 1, 1),
  ('item-memory-stick', 'Memory stick', 'cat-business', 1, 0),

  ('item-laptop-cable', 'Charging cable — laptop', 'cat-electronics', 1, 1),
  ('item-phone-cable', 'Charging cable — phone', 'cat-electronics', 1, 1),
  ('item-watch-cable', 'Charging cable — watch', 'cat-electronics', 1, 0),
  ('item-phone', 'Phone', 'cat-electronics', 1, 1),
  ('item-power-adapter', 'Travel power adapter', 'cat-electronics', 1, 0),

  ('item-walking-shoes', 'Walking shoes', 'cat-shoes', 1, 0),
  ('item-sport-shoes', 'Sport shoes', 'cat-shoes', 1, 0),
  ('item-dress-shoes', 'Dress shoes', 'cat-shoes', 1, 0),
  ('item-sandals', 'Sandals', 'cat-shoes', 1, 0),
  ('item-flip-flops', 'Flip-flops', 'cat-shoes', 1, 0),
  ('item-house-shoes', 'House shoes', 'cat-shoes', 1, 0),

  ('item-shorts', 'Shorts', 'cat-clothes', 3, 0),
  ('item-tshirts', 'T-shirts', 'cat-clothes', 5, 0),
  ('item-pyjamas', 'Pyjamas', 'cat-clothes', 1, 0),
  ('item-socks', 'Socks', 'cat-clothes', 6, 0),
  ('item-underwear', 'Underwear', 'cat-clothes', 6, 0),
  ('item-sweater', 'Sweater / warm layer', 'cat-clothes', 1, 0),
  ('item-rain-jacket', 'Rain jacket', 'cat-clothes', 1, 0),

  ('item-towels', 'Towels', 'cat-beach', 1, 0),
  ('item-swimwear', 'Swimwear', 'cat-beach', 1, 0),
  ('item-beach-bag', 'Beach bag', 'cat-beach', 1, 0),

  ('item-daypack', 'Daypack', 'cat-adventure', 1, 0),
  ('item-hiking-poles', 'Hiking poles', 'cat-adventure', 1, 0),
  ('item-headlamp', 'Headlamp', 'cat-adventure', 1, 0),

  ('item-camera', 'Camera', 'cat-camera', 1, 0),
  ('item-camera-charger', 'Camera charger', 'cat-camera', 1, 0),
  ('item-memory-cards', 'Camera memory cards', 'cat-camera', 2, 0),
  ('item-camera-batteries', 'Camera batteries', 'cat-camera', 2, 0),

  ('item-toothbrush', 'Toothbrush', 'cat-toiletries', 1, 1),
  ('item-nail-clipper', 'Nail clipper', 'cat-toiletries', 1, 0),
  ('item-forceps', 'Forceps / tweezers', 'cat-toiletries', 1, 0),
  ('item-deodorant', 'Deodorant', 'cat-toiletries', 1, 0),
  ('item-toothpaste', 'Toothpaste', 'cat-toiletries', 1, 0),
  ('item-soap', 'Soap', 'cat-toiletries', 1, 0),
  ('item-razor', 'Razor', 'cat-toiletries', 1, 0),

  ('item-pain-killers', 'Pain killers', 'cat-medication', 1, 0),
  ('item-antibiotics', 'Antibiotics', 'cat-medication', 1, 0),
  ('item-sleeping-meds', 'Sleeping medication', 'cat-medication', 1, 0),
  ('item-melatonin', 'Melatonin', 'cat-medication', 1, 0),
  ('item-disinfectant', 'Disinfectant', 'cat-medication', 1, 0),
  ('item-sunscreen', 'Sunscreen', 'cat-medication', 1, 0),
  ('item-bug-spray', 'Bug spray', 'cat-medication', 1, 0),
  ('item-glasses', 'Glasses', 'cat-medication', 1, 1),
  ('item-contact-lenses', 'Contact lenses', 'cat-medication', 1, 0),

  ('item-little-pillow', 'Little travel pillow', 'cat-comfort', 1, 0),
  ('item-eye-mask', 'Eye mask', 'cat-comfort', 1, 0),
  ('item-ear-plugs', 'Ear plugs', 'cat-comfort', 1, 0),

  ('item-laundry-bag', 'Laundry bag', 'cat-misc', 1, 0),
  ('item-pen', 'Pen', 'cat-misc', 1, 0);
